server:
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lockerserver?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
websocket:
  maxTimeout: 120000
fastlockerserver:
  id: 2
  name: 华南服务器
  api: /park
  maxsize: 100

register:
  onlineapi: ws://127.0.0.1:8083/server/online/
  #  onlineapi: ws://192.168.1.103:81/regist
  #onlineapi: ws://192.168.1.105:8083/server/online/